# Generated by Django 6.0.7 on 2026-07-15 13:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_posted',
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes_number',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='review.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'review'), name='uniq_user_review_post')],
            },
        ),
    ]
