# Generated by Django 6.0.7 on 2026-07-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_postcomment_postcommentlike_postlike_reviewcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
