# Generated by Django 6.0.7 on 2026-07-17 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_logo'),
        ('review', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('SALARIES', 'Salaries'), ('CULTURE', 'Culture'), ('MANAGEMENT', 'Management'), ('POLICIES', 'Policies'), ('GROWTH', 'Growth'), ('INTERVIEWS', 'Interviews'), ('ISSUES', 'Issues'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='company.company'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='review.post'),
        ),
    ]
