# Generated by Django 6.0.7 on 2026-07-17 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_logo'),
        ('review', '0006_post_category_post_company_post_is_anonymous_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popularity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-creation'], name='post_creation_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-popularity_score', '-creation'], name='post_pop_creation_idx'),
        ),
    ]
