# Generated by Django 6.0.7 on 2026-07-18 12:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_industry'),
        ('review', '0007_post_popularity_score_post_post_creation_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNestedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_title', models.CharField(max_length=255)),
                ('likes_number', models.IntegerField(default=0)),
                ('parent_comment_author_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewNestedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_title', models.CharField(max_length=255)),
                ('likes_number', models.IntegerField(default=0)),
                ('parent_comment_author_id', models.IntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='post_user_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['post'], name='postcomment_post_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewcomment',
            index=models.Index(fields=['review'], name='reviewcomment_review_idx'),
        ),
        migrations.AddField(
            model_name='postnestedcomment',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nested_comments', to='review.postcomment'),
        ),
        migrations.AddField(
            model_name='postnestedcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_nested_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewnestedcomment',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nested_comments', to='review.reviewcomment'),
        ),
        migrations.AddField(
            model_name='reviewnestedcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_nested_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='postnestedcomment',
            index=models.Index(fields=['parent_comment'], name='postnested_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewnestedcomment',
            index=models.Index(fields=['parent_comment'], name='revnested_parent_idx'),
        ),
    ]
