# Generated by Django 6.0.7 on 2026-07-18 12:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_postnestedcomment_reviewnestedcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postnestedcomment',
            name='parent_comment_author_id',
        ),
        migrations.RemoveField(
            model_name='reviewnestedcomment',
            name='parent_comment_author_id',
        ),
        migrations.AddField(
            model_name='postnestedcomment',
            name='parent_comment_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_parent_nested_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewnestedcomment',
            name='parent_comment_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_parent_nested_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='creation',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PostNestedCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_nested_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_nested_comment_likes', to='review.postnestedcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_nested_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'post_nested_comment'), name='uniq_user_post_nested_comment_like')],
            },
        ),
        migrations.CreateModel(
            name='ReviewNestedCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_nested_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_nested_comment_likes', to='review.reviewnestedcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_nested_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'review_nested_comment'), name='uniq_user_review_nested_comment_like')],
            },
        ),
    ]
