# Generated by Django 6.0.7 on 2026-07-18 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_industry'),
        ('review', '0009_remove_postnestedcomment_parent_comment_author_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category'], name='post_category_idx'),
        ),
    ]
