# Generated by Django 6.0.7 on 2026-07-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0021_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='uniq_user_review_post',
        ),
    ]
