# Generated by Django 6.0.7 on 2026-07-18 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['industry'], name='company_industry_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['-current_rate'], name='company_rate_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='company_name_idx'),
        ),
    ]
