# Generated by Django 6.0.7 on 2026-07-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_company_industry_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('SOFTWARE_DEV', 'Software Development & AI'), ('IT_SERVICES', 'IT Services & Consulting'), ('INTERNET_SAAS', 'Internet & SaaS Platforms'), ('TELECOM', 'Telecommunications & Networking'), ('CYBERSECURITY', 'Cybersecurity'), ('GAME_DEV', 'Game Development'), ('MEDIA_PROD', 'Media Production & Content'), ('BANKING', 'Banking & Financial Institutions'), ('INVESTMENT', 'Investment & Asset Management'), ('FINTECH', 'Financial Technology (FinTech)'), ('INSURANCE', 'Insurance'), ('VENTURE_CAPITAL', 'Venture Capital & Private Equity'), ('ACCOUNTING', 'Accounting & Auditing'), ('CONSULTING', 'Management Consulting'), ('LEGAL', 'Legal Services'), ('HR_RECRUITING', 'Human Resources & Recruiting'), ('MARKETING_ADV', 'Marketing, Advertising & PR'), ('DESIGN_UX', 'Design & UI/UX'), ('HOSPITALS', 'Hospitals & Medical Care'), ('PHARMA', 'Pharmaceuticals'), ('MEDICAL_DEVICES', 'Medical Devices'), ('BIOTECH', 'Biotechnology & Research'), ('MANUFACTURING', 'General Manufacturing'), ('AUTOMOTIVE', 'Automotive & Vehicles'), ('AEROSPACE', 'Aerospace & Defense'), ('ELECTRONICS', 'Electronics & Appliances'), ('CHEMICALS', 'Chemicals & Petrochemicals'), ('TEXTILES', 'Textiles, Apparel & Fashion'), ('FURNITURE_MFG', 'Furniture & Wood Product Manufacturing'), ('E_COMMERCE', 'E-Commerce'), ('RETAIL', 'Retail Stores & Malls'), ('WHOLESALE', 'Wholesale & Distribution'), ('FMCG', 'Fast-Moving Consumer Goods (FMCG)'), ('FURNITURE_RETAIL', 'Furniture & Home Furnishings Retail'), ('CONSTRUCTION', 'Construction & Civil Engineering'), ('REAL_ESTATE', 'Real Estate Development & Brokerage'), ('ARCHITECTURE', 'Architecture & Urban Planning'), ('LOGISTICS', 'Logistics & Supply Chain'), ('TRANSPORTATION', 'Freight & Transportation'), ('AVIATION', 'Airlines & Aviation Services'), ('OIL_GAS', 'Oil & Gas'), ('RENEWABLE_ENERGY', 'Renewable Energy & Environment'), ('UTILITIES', 'Utilities (Power, Water, Waste)'), ('MINING_METALS', 'Mining & Metals'), ('HOSPITALITY', 'Hotels, Tourism & Hospitality'), ('FOOD_BEVERAGE', 'Restaurants & Food Services'), ('ENTERTAINMENT', 'Entertainment, Arts & Gaming'), ('SPORTS', 'Sports & Fitness'), ('HIGHER_EDUCATION', 'Higher Education & Universities'), ('K12_EDUCATION', 'Primary & Secondary Education'), ('E_LEARNING', 'E-Learning & EdTech'), ('GOVERNMENT', 'Government & Public Sector'), ('NON_PROFIT', 'NGOs & Non-Profit Organizations'), ('INTERNATIONAL_AFFAIRS', 'International Affairs & Diplomacy'), ('AGRICULTURE', 'Agriculture, Livestock & Forestry'), ('OTHER', 'Other Industries')], default='OTHER', max_length=100),
        ),
    ]
