# Generated by Django 6.0.7 on 2026-07-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_initial'),
        ('review', '0014_remove_post_post_creation_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='company_industry_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='company_rate_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='company_name_idx',
        ),
        migrations.RemoveConstraint(
            model_name='company',
            name='unique_company_name_industry',
        ),
        migrations.RemoveConstraint(
            model_name='companyrate',
            name='unique_user_company_rate',
        ),
        migrations.RemoveField(
            model_name='companyrate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyrate',
            name='user',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyRate',
        ),
    ]
