# Generated by Django 6.0.7 on 2026-07-24 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0013_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyrate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='company.company'),
        ),
        migrations.AddField(
            model_name='companyrate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['industry'], name='company_industry_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['-current_rate'], name='company_rate_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='company_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('name', 'industry'), name='unique_company_name_industry'),
        ),
        migrations.AddConstraint(
            model_name='companyrate',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='unique_user_company_rate'),
        ),
    ]
