# Generated by Django 6.0.7 on 2026-07-18 22:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='creation',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
