# Generated by Django 6.0.7 on 2026-07-21 11:43

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_creation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='review',
        ),
        migrations.AddField(
            model_name='notification',
            name='partner_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='partner_type',
            field=models.CharField(blank=True, choices=[('POST', 'Post'), ('REVIEW', 'Review'), ('COMPANY', 'Company'), ('USER', 'User')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-creation'], name='notif_user_creation_idx'),
        ),
    ]
