# Generated by Django 6.0.7 on 2026-07-21 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_post_remove_notification_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'partner_id', 'partner_type', '-creation'], name='notif_partner_lookup_idx'),
        ),
    ]
