# Generated by Django 6.0.7 on 2026-07-24 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0005_remove_notification_notif_user_creation_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('partner_id', models.BigIntegerField(blank=True, null=True)),
                ('partner_type', models.CharField(blank=True, choices=[('POST', 'Post'), ('REVIEW', 'Review'), ('COMPANY', 'Company'), ('USER', 'User')], max_length=50, null=True)),
            ],
        ),
    ]
