# Generated by Django 6.0.7 on 2026-07-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_user_creation_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_partner_lookup_idx',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
