# Generated by Django 6.0.7 on 2026-07-24 13:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0014_remove_notification_notif_user_creation_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('partner_id', models.BigIntegerField(blank=True, null=True)),
                ('partner_type', models.CharField(blank=True, choices=[('POST', 'Post'), ('REVIEW', 'Review'), ('COMPANY', 'Company'), ('USER', 'User')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-creation'], name='notif_user_creation_idx'), models.Index(fields=['user', 'partner_id', 'partner_type', '-creation'], name='notif_partner_lookup_idx')],
            },
        ),
    ]
